version: '3'
services:
    beer-rating-project:
        build: .
        env_file:
            - ".env"
        image: beer-rating-project
        command: beer-rating-project
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - beer-rating-project
